### ISSUE TITLE
Peer to peer morning review

### ISSUE THREAD

**Issue by Yothu** [JohnFTitor/capstoneProject_first#7]
I would recommend adding links to each sponsor image in the partners' section.

**Comment by lisandroseia** [comment]
I think it would be better if the user have a way to read all the speaker information on mobiles.
Besides that, you could make the links on the header that takes you to the correct section.
You can also change the scroll behavior to do it smoother.

**Comment by Bondok6** [comment]
## Hi @JohnFTitor 👋

## Your Project is amazing 🔥

## Suggestions

- You can change the structure of the `speaker section` in js file to be more readable.
- [optional] I think it would be better to make the scroll behavior smooth using this property `scroll-behavior: smooth`

<img src="https://media0.giphy.com/media/VJ5pkHokJgV78qy70E/giphy.gif"/>

**Comment by JohnFTitor** [comment]
Thanks, Guys! I will implement these changes

<img src="https://media4.giphy.com/media/xDbS5VgmigHgk/giphy.gif"/>

**Comment by JohnFTitor** [comment]
Changes implemented in pull request #8. Thanks again for the review!

<img src="https://media3.giphy.com/media/GcLLdwoMWd2A8/giphy.gif"/>
